-
  name: Playbook deploy via ansible
  hosts: group_env_deploy #hosts represente les hosts def dans targets.txt avec l'alias group1
  become: yes
  vars:
    directory_deploy: "deploy"
    file_yaml: "game-dpl.yml"
    APP_VERSION: "APP_VERSION_LAST_BUILD"
    path_deploy: "/home/jenkins/"
    
  tasks:
    - name: Test ping
      ping:
    
    - name: create folder
      file: path={{directory_deploy}} state=directory

    - name: copy file
      copy: src={{file_yaml}} dest={{directory_deploy}}
        
    - name: Deploy application v1
      shell: sed -i "s/APP_VERSION/{{APP_VERSION}}/g" {{path_deploy}}{{directory_deploy}}/game-dpl.yml
    
    - name: Deploy application v2
      shell: kubectl apply -f {{path_deploy}}{{directory_deploy}}/game-dpl.yml